/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author dougl
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        passwordTitle = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        loginSubtitle = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameTitle = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        passwordTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 700, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(null);

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setLayout(null);
        form.add(passwordField);
        passwordField.setBounds(108, 412, 464, 40);

        passwordTitle.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        passwordTitle.setText("Senha");
        form.add(passwordTitle);
        passwordTitle.setBounds(108, 362, 140, 20);

        loginButton.setBackground(new java.awt.Color(60, 66, 108));
        loginButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Sign in");
        form.add(loginButton);
        loginButton.setBounds(110, 560, 460, 41);
        form.add(separator);
        separator.setBounds(108, 524, 464, 20);

        loginSubtitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginSubtitle.setForeground(new java.awt.Color(153, 153, 153));
        loginSubtitle.setText("<html><p>Acesse seu plano de saúde. Explore seu gerenciador de consultas e exames.</p><html>");
        form.add(loginSubtitle);
        loginSubtitle.setBounds(110, 180, 464, 45);

        loginTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        loginTitle.setText("<html><p>Faça seu login</p></html>");
        loginTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        form.add(loginTitle);
        loginTitle.setBounds(110, 110, 340, 60);

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        form.add(usernameField);
        usernameField.setBounds(108, 295, 464, 40);

        usernameTitle.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        usernameTitle.setText("Usuário");
        form.add(usernameTitle);
        usernameTitle.setBounds(108, 257, 140, 20);

        showPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        showPassword.setText("Mostrar senha");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        form.add(showPassword);
        showPassword.setBounds(447, 470, 125, 21);

        passwordTitle1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        passwordTitle1.setForeground(new java.awt.Color(109, 180, 227));
        passwordTitle1.setText("Cadastra-se");
        form.add(passwordTitle1);
        passwordTitle1.setBounds(460, 630, 100, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel1.setText("Ainda não tem conta?");
        form.add(jLabel1);
        jLabel1.setBounds(300, 630, 150, 22);

        getContentPane().add(form);
        form.setBounds(0, 0, 680, 740);

        setSize(new java.awt.Dimension(697, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if(showPassword.isSelected()) {
            passwordField.setEchoChar('\0');
        } else {
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginSubtitle;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JLabel passwordTitle1;
    private javax.swing.JSeparator separator;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameTitle;
    // End of variables declaration//GEN-END:variables
}
