/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author dougl
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        passwordTitle = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        loginSubtitle = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameTitle = new javax.swing.JLabel();
        usernameField1 = new javax.swing.JTextField();
        usernameTitle1 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        passwordTitle1 = new javax.swing.JLabel();
        usernameField2 = new javax.swing.JTextField();
        usernameTitle2 = new javax.swing.JLabel();
        passwordTitle2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 800));
        setSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(null);

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setLayout(null);
        form.add(passwordField);
        passwordField.setBounds(110, 520, 464, 40);

        passwordTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        passwordTitle.setForeground(new java.awt.Color(51, 51, 51));
        passwordTitle.setText("Repita sua senha:");
        form.add(passwordTitle);
        passwordTitle.setBounds(110, 490, 150, 20);

        loginButton.setBackground(new java.awt.Color(60, 66, 108));
        loginButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Inscrever-se");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        form.add(loginButton);
        loginButton.setBounds(370, 600, 210, 41);
        form.add(separator);
        separator.setBounds(110, 540, 464, 20);

        loginSubtitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginSubtitle.setForeground(new java.awt.Color(153, 153, 153));
        loginSubtitle.setText("Inscreva-se para começar");
        form.add(loginSubtitle);
        loginSubtitle.setBounds(240, 120, 180, 20);

        loginTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        loginTitle.setText("<html><p>Crie sua conta</p></html>");
        loginTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        form.add(loginTitle);
        loginTitle.setBounds(180, 70, 340, 40);

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        form.add(usernameField);
        usernameField.setBounds(110, 190, 464, 40);

        usernameTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        usernameTitle.setForeground(new java.awt.Color(51, 51, 51));
        usernameTitle.setText("Nome:");
        form.add(usernameTitle);
        usernameTitle.setBounds(110, 160, 140, 20);

        usernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField1ActionPerformed(evt);
            }
        });
        form.add(usernameField1);
        usernameField1.setBounds(110, 270, 464, 40);

        usernameTitle1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        usernameTitle1.setForeground(new java.awt.Color(51, 51, 51));
        usernameTitle1.setText("E-mail:");
        form.add(usernameTitle1);
        usernameTitle1.setBounds(110, 240, 140, 20);
        form.add(passwordField1);
        passwordField1.setBounds(110, 430, 464, 40);

        passwordTitle1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        passwordTitle1.setForeground(new java.awt.Color(109, 180, 227));
        passwordTitle1.setText("Faça seu login ao invés disso");
        form.add(passwordTitle1);
        passwordTitle1.setBounds(110, 610, 230, 20);

        usernameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField2ActionPerformed(evt);
            }
        });
        form.add(usernameField2);
        usernameField2.setBounds(110, 350, 464, 40);

        usernameTitle2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        usernameTitle2.setForeground(new java.awt.Color(51, 51, 51));
        usernameTitle2.setText("Telefone:");
        form.add(usernameTitle2);
        usernameTitle2.setBounds(110, 320, 140, 20);

        passwordTitle2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        passwordTitle2.setForeground(new java.awt.Color(51, 51, 51));
        passwordTitle2.setText("Senha:");
        form.add(passwordTitle2);
        passwordTitle2.setBounds(110, 400, 140, 20);

        getContentPane().add(form);
        form.setBounds(0, -20, 680, 740);

        setSize(new java.awt.Dimension(697, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void usernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField1ActionPerformed

    private void usernameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField2ActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel form;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginSubtitle;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JLabel passwordTitle1;
    private javax.swing.JLabel passwordTitle2;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usernameField1;
    private javax.swing.JTextField usernameField2;
    private javax.swing.JLabel usernameTitle;
    private javax.swing.JLabel usernameTitle1;
    private javax.swing.JLabel usernameTitle2;
    // End of variables declaration//GEN-END:variables
}
